backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "settings"
    label: "Paramètres"
    files:
      - label: "Configuration générale"
        name: "general"
        file: "content/settings/general.md"
        fields:
          - {label: "Logo", name: "logo", widget: "image", required: true}
          - {label: "Téléphone", name: "phone", widget: "string", required: true}
          - {label: "Email", name: "email", widget: "string", required: true}
          - {label: "Adresse", name: "address", widget: "text", required: true}

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description SEO", name: "description", widget: "text"}
      - {label: "Image en-tête", name: "headerImage", widget: "image"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Ordre dans le menu", name: "menuOrder", widget: "number"}
      - {label: "Publié", name: "published", widget: "boolean", default: true}

  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Prix", name: "price", widget: "string"}
      - label: "Caractéristiques"
        name: "features"
        widget: "list"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}

  - name: "blog"
    label: "Articles Blog"
    folder: "content/blog"
    create: true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Contenu", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "cities"
    label: "Villes"
    folder: "content/cities"
    create: true
    fields:
      - {label: "Nom", name: "name", widget: "string"}
      - {label: "Code Postal", name: "postalCode", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}
      - label: "Services Spécifiques"
        name: "services"
        widget: "list"
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}